# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellBuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='previous_price',
            field=models.FloatField(default=1000.0),
        ),
    ]
