# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellBuy', '0002_share_previous_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuserholding',
            name='current_holding',
            field=models.FloatField(default=25000.0),
        ),
        migrations.AlterField(
            model_name='userholding',
            name='holding',
            field=models.FloatField(default=25000.0),
        ),
    ]
