# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('username', models.CharField(max_length=120)),
                ('college', models.CharField(max_length=120)),
                ('branch', models.CharField(max_length=120)),
                ('email', models.CharField(max_length=120)),
                ('contact', models.DecimalField(decimal_places=0, max_digits=11)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
