# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-21 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
