# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginRegister', '0002_auto_20180821_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
